// <auto-generated />
namespace EFTask.netfarmework.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddMemberInBorrow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddMemberInBorrow));
        
        string IMigrationMetadata.Id
        {
            get { return "202407261335457_AddMemberInBorrow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
